name: Deploy

on: [pull_request]

permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: 'Authenticate to GCP'
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/412761838122/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: 'github-actions@warm-particle-425311-e7.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud secrets versions access "latest" --secret "my-secret"

    - name: build and push the docker image
      run: |
        docker build -t europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest .
        docker push europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-client --image europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest --region europe-west9 --platform=managed --allow-unauthenticated
