name: Deploy

on:
  push:
    branches:
      - 'develop'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - name: install the gcloud cli
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev
        docker build -t europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-client/image-api-client:latest .
        docker push europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-client/image-api-client:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-client --image europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-client/image-api-client:latest --region  europe-west9 --platform managed --allow-unauthenticated 
