name: Deploy

on:
  push:
    branches:
      - 'develop'

permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: 'Authenticate to GCP'
      id: auth
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/412761838122/locations/global/workloadIdentityPools/pool/providers/provider-pool"'
        service_account: 'python@warm-particle-425311-e7.iam.gserviceaccount.com'

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: 'europe-west9-docker.pkg.dev'

    - name: build and push the docker image
      run: |
        docker build -t europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest .
        docker push europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-client --image europe-west9-docker.pkg.dev/warm-particle-425311-e7/api-client/image-api-client:latest --region europe-west9 --platform=managed --allow-unauthenticated
