name: Deploy

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
      create_credentials_file: 'true'
      workload_identity_provider: 'projects/412761838122/locations/global/workloadIdentityPools/pool/providers/provider-pool"'
      service_account: 'python@warm-particle-425311-e7.iam.gserviceaccount.com'
    - name: 'gcloud'
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list --project cloudquicklab
    - name: code checkout
      uses: actions/checkout@v4

    - name: install the gcloud cli
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev
        docker build -t europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-client/image-api-client:latest .
        docker push europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-client/image-api-client:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-client --image europe-west9-docker.pkg.dev/ancient-tractor-411414/api-client/image-api-client:latest --region europe-west9 --platform=managed --allow-unauthenticated
